# Generated by Django 3.2.9 on 2021-11-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='epense_type',
            new_name='expense_type',
        ),
    ]
